version: '3'
services:
  web:
    image:  nginx
    container_name: nginx_server
  db:
    image: mysql
    container_name: mysql_server 
    ports:
    - "3308:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
